program: src/dtu_mlops_project/train.py
method: random

metric:
  goal: maximize
  name: val/acc

parameters:
  model.optimizer.lr:
    distribution: log_uniform_values
    max: 0.1
    min: 0.0001
  model.optimizer.weight_decay:
    max: 0.001
    min: 0.0
  data.batch_size:
    values: [16, 32, 64]

command:
#  - ${env}
  - uv
  - run
  - python
  - ${program}
  - model=cnn
  - trainer.max_epochs=10
  - +trainer.limit_train_batches=0.5
  - logger=wandb
  - ${args_no_hyphens}
