_target_: src.dtu_mlops_project.model.C8SteerableCNN

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  input_channels: 1
  num_classes: 10

#Usage is
#uv run python src/dtu_mlops_project/train.py model=c8 trainer.max_epochs=1
