name: "linting and typing"

on:
  push:
    branches:
      - [master, main]
  pull_request:
    branches:
      - [master, main]

jobs:
  format:
    name: linting and typing
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v4

          - name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
              enable-cache: true

          - name: Set up Python
            run: uv python install 3.12

          - name: Install dependencies
            run: |
              uv venv
              uv pip install ruff

          - name: Run ruff check
            run: uv venv && uv pip list && .venv/bin/ruff check .

          - name: Run ruff format
            run: .venv/bin/ruff format --check .

          - name: Run mypy
            run: .venv/bin/mypy src/dtu_mlops_project tests
